### ISSUE TITLE
HTPC dont shutdown after epg update

### ISSUE THREAD

**Issue by hobbypunk90** [Helly1206/service.hts.pvrmanager#2]
Hello,

i let update my HTPCs(arch linux) epg data every 5 days at 6 o'clock, i think since the update to Kodi 15, the PC don't shutdown after the update of the epg data. not sure y, only log entry is:
**06:00:32 T:139782821742336  NOTICE: service.hts.pvrmanager: Starting service (578)**

after that the pvrmanager never write anything to the log again.

**Comment by Helly1206** [comment]
Hi Hobbypunk90,

Thanks for using and debugging this addon.

I never use the epg-update functionality myself, so that is why I didn't notice this bug. I will have a look at it at a later stage and fix it at a next release.

Helly.

**Comment by hobbypunk90** [comment]
thanks :) i love your addon, its great.

**Comment by Helly1206** [comment]
Hi hobbypunk90,

I'm sorry it took a while, but I released a new version of the PVR manager.

There was a bug in calculating the time for the EPG update. Therefore the script never knows an update is started and no shutdown is issued after finish.

Thanks for your input.

Helly.

**Comment by hobbypunk90** [comment]
thanks i'll try it ;)
