### ISSUE TITLE
no shutdown on EPGupdate, when addon can't connect to tvheadend

### ISSUE THREAD

**Issue by hobbypunk90** [Helly1206/service.hts.pvrmanager#4]
hey, it's me again ;) :D

like the title said ;) when tvheadend answers with a 401(or a 1), the system don't shutdown after the time.

Greets,
Marcel

**Comment by Helly1206** [comment]
Ok, You've found another one. I'll have a look later on.

Thanks,
Helly.

**Comment by Helly1206** [comment]
Hi,

I was checking your issue and my system does shutdown when tvheadend is not running. I case of EPG it should not matter whether or not tvheadend is running.

Could you send me the logfile (.kodi/temp/service.hts.pvrmanager/service.hts.pvrmanager.log) when this happens? Then I can try to find the cause from the logfile.

Thanks,
Helly.

**Comment by hobbypunk90** [comment]
Hmm, I think this was an other problem, I can't reproduce it 😕 very strange...

**Comment by Helly1206** [comment]
Ok, no problem.

Thanks,
Helly.
